
<!DOCTYPE html>
<html>
 <?php include'head.php'; ?>
	<body>
	
		<!-- LOADER -->	
		<div id="loader-overflow">
      <div id="loader3">Please enable JS</div>
    </div>	

		<div id="wrap" class="boxed ">
			<div class="grey-bg"> <!-- Grey BG  -->	
				<!-- HEADER 1 NO-TRANSPARENT -->
        <?php include'header.php'; ?>
				
        <!-- Content -->
        <!-- PAGE TITLE LARGE IMG -->
        <div class="page-title-cont page-title-large grey-dark-bg page-title-img  pt-250">
          <div class="relative container align-left">
            <div class="row">
               
              <div class="col-md-8">
                <h1 class="page-title">ABOUT US</h1>
                <div class="page-sub-title">
                  Just a little background from yours trully!
                </div>
              </div>
               
              <div class="col-md-4">
                <div class="breadcrumbs">
                  <a href="index.php">Home</a><span class="slash-divider">/</span> <a href="About.php"> <span class="bread-current" >ABOUT ME</a></span>
                </div>
              </div>
              
            </div>
          </div>
        </div>
 
        <!-- COTENT CONTAINER -->
        <div class="container p-140-cont pb-0">
          <div class="row">
            <div class="col-md-12">
              <img src="images/lead/about_us.jpg" alt="Ipsum">
            </div>
          </div>
        </div>
      
        <!-- FEATURES 10 -->
        <div id="about" class="page-section p-110-cont">
					<div class="container">

            <div class="row">
              <!-- TESTIMONIALS -->
              <div class="col-md-12 pt-30 pb-40">
										<!-- <div><h3> <strong>About Us</strong></span> </h3> </div> -->
                    <p> <h5>LeadHustler is the number one source for telemarketing leads of any kinds. We have been in the business for more than 13 years. We believe in 100% customer satisfaction and we strive to deliver our leads with the highest quality. All of our calls are recorded and the audio recording is checked by our quality control team before we send them to our customers. If they did not meet our quality standards, they will not be sent to our customers. That is how serious we are about quality. </h5></p>
                    <p> <h5>LeadHustler understands that getting sales lead is important for your business. We provide sales lead for telemarketers. All you have to do is contact us and order sales leads according to your business. We can provide health insurance leads, storm damage leads, hail damage, solar leads, or even home security leads. </h5></p>
                    <p> <h5>You don’t have to worry about getting reliable telemarketing leads for your business. We provide you the BEST contacts with pricing so you can get the most of your pocket. We value customer satisfaction and we only want to provide the best for them. </h5> </p>
                    <p> <h5>We have a variety of services for your business, such as outbound calling, inbound customer, receptionist services, appointment setting, personal assistant, web design, social networking leads, digital media management, as well as Search Engine Optimization (SEO) leads. You can find out more about our services in our service page, where there will be more explanation about each service that we offer. </h5> </p>
                    <p> <h5>All of our leads are not generated by online search or by online survey. Instead, we only use telemarketing to ensure that we will get the highest quality information. We also don’t use any third party in the data gathering process, because as the number one outsourcing facility, we keep everything in-house. This also means that we can take control of our quality process and also we can keep our prices competitive. Using telemarketing also can boost trust for the potential customers rather than filling in an online survey </h5> </p>
                    <p> <h5>We are also experienced in providing training for sales reps and insurance agents. LeadHustler offers you a one-stop shopping place for all your leads. We also have experience in working with many clients, from small business to the biggest players in the industry. </h5> </p>
</div>
</div>
</div>
</div>
              <!-- FEATURES -->
						  <div class="container p-30-cont pb-0">
                <div class="row">
                <div class="col-md-12 col-sm-6 pb-0" style="margin-right: 20px;">
                  <div class="fes5-box wow fadeIn" >
                <h4> <strong style="text-transform: uppercase;">Goals of the Website </strong></h4>
              </div>  
              </div>
                  <div class="col-md-12 col-sm-6 pb-10">
                    <div class="fes5-box wow fadeIn" >
                      <h3><i class="fa fa-check" aria-hidden="true"> <strong> IMPROVE TRAINING PERFORMANCE </strong> </i></h3>
                      <p>For this is a training website exclusively for Leadhustler Only!</p>
                    </div>
                  </div>
                      
                  <div class="col-md-6 col-sm-12 pb-10">
                    <div class="fes5-box wow fadeIn" data-wow-delay="200ms">
                    <h3><i class="fa fa-check" aria-hidden="true"> <strong> REACH TARGET GOALS</strong> </i></h3>
                      <p>You'll never have time slacking use this to train!</p>
                    </div>
                  </div>
                      
                </div>
                    
                <div class="row">
                    
                  <div class="col-md-12 col-sm-12 mb-10" style="padding-bottom: 30px;">
                    <div class="fes5-box wow fadeIn" data-wow-delay="400ms">
                    <h3><i class="fa fa-check" aria-hidden="true"> <strong> EARN MORE MONEY </strong> </i></h3>
                      <p>Because you will never do something you're good at for free!</p>
                    </div>
                  </div>
                      
                  <!-- <div class="col-md-6 col-sm-6 pb-10">
                    <div class="fes5-box wow fadeIn"  data-wow-delay="600ms">
                      <h3>EASY TO CUSTOMIZE</h3>
                      <p>Sed ut perspiciatis unde omnis iste nat eror acus  antium que</p>
                    </div>
                  </div> -->
                  
                </div>                    
                    
							</div>
              
						</div>
					</div>
				</div>

        <!-- FEATURES 7 -->
        <div class="page-section grey-light-bg clearfix">
          <div class="fes7-img-cont col-md-5">
            <div class="fes7-img" style="background-image: url(images/found.png)"></div>
          </div>
          
          <div class="container">
            <div class="row">
              <div class="col-md-6  col-md-offset-6 fes7-text-cont p-80-cont">
                <h1><span class="font-light" style="text-transform: uppercase;"><strong>The Founders Message</strong></span></h1>
                <p style="margin-bottom: 15px">
                  "I believe many business owners know that the driving force of any sales organization is having good quality leads. 
                  Without people to contact and sell your products and services, your business will not survive. I used to make cold calls up to 150 calls a day which would generate leads but I know it was not a good use of time since I was spending more time prospecting and less time closing. I know that sales people don’t get paid to prospects, but to close deals. I needed good quality health insurance leads to grow and expand my business. I was trying different ways to generate leads, so I decided on buying internet leads as a way of trying to increase sales for me and my organization. I later found out that the quality of the leads was terrible and I felt like I was flushing my money down the toilet. Most of the leads I got were people getting tricked to give their information for a contest or to win a free computer, and by the time I reached the client, they already had 7 other brokers called them and they already got health insurance. I felt very frustrated and realized that I had to do something different. I know that I needed to get out of the box and do something different than my competitors.
                </p>
                <p style="margin-bottom: 15px">
                I decided to do a research on the most successful Fortune 500 companies in the world. I wanted to know how they always managed to stay one step ahead. The answer is OUTSOURCING. Those companies are employing people in different countries to do some of their basic tasks for them. This may include tasks such as customer service, lead generation, technical assistance, data processing, and others. These tasks can simply be done over the internet or phone. Having an outsourcing team means that they can get the job done with fewer cost compared to having full-time American employees.
                </p>
                <p style="margin-bottom: 15px">
                While I thought it’s a smart move to use a global system that can benefit the company, at that time my company was just a small one with three employees. I didn’t have a budget like those Fortune 500 companies! I even tried to contact some call centers, only to found out that they have a minimum of 1000 leads a month, something that my company did not have the capacity for. I got even more frustrated. I know that there a lot of small companies out there that could really benefit from having an outsource system like the “big boys” were using.
                </p>
                <p style="margin-bottom: 15px">
                I continued to do my research until I finally had enough knowledge and made a big decision. In March 2005 I got on a plane to the Philippines to see the outsourcing process myself. During my time in the Philippines, I learned how I would win the leads war and gain a competitive advantage over my competitors. I know I had to do something extremely risky, but as they say the bigger the risk, the bigger the rewards! I opened my own call center in December 2005. Opening a call center in a foreign country was no easy task, I had to face lots of uphill battle and had to go through a lot, but it is worth it in the end. By taking advantage of the global economy and having my own call center, I was able to create leads with less cost than when I had to buy them. More importantly, I was able to control the quality.
                </p>
                <p style="margin-bottom: 15px">
                While the economy is down and a lot of businesses were struggling, I decided to open the opportunity to other businesses. I gave them the opportunity to take advantage of the global economy without having to move to a third world country. My core focus was to help small businesses and entrepreneurs grow and expand their businesses. I want them to be able to hire more workers and gain a competitive advantage over their competitors. I understand that we are facing tough times in the industry, so I want to help you to cut costs and increase your efficiency as it is more important now than ever. Call us and we can help you not only to survive in this economy but to thrive against your competitors!"
                </p>
                <!-- <div>
                    
                  <div class="col-md-6 col-sm-6">
                    <div class="fes7-box wow fadeIn" >
                      <div class="fes7-box-icon">
                        <div class="icon icon-ecommerce-graph-increase"></div>
                      </div>
                      <h3>SEO Friendly</h3>
                      <p>Sed ut perspiciatis unde omnis iste nat eror acus  antium que</p>
                    </div>
                  </div>
                      
                  <div class="col-md-6 col-sm-6">
                    <div class="fes7-box wow fadeIn" data-wow-delay="200ms">
                      <div class="fes7-box-icon">
                        <div class="icon icon-software-font-smallcaps"></div>
                      </div>
                      <h3>Google Fonts</h3>
                      <p>Sed ut perspiciatis unde omnis iste nat eror acus  antium que</p>
                    </div>
                  </div>
                      
                </div>
                    
                <div class="row">
                    
                  <div class="col-md-6 col-sm-6">
                    <div class="fes7-box wow fadeIn" data-wow-delay="400ms">
                      <div class="fes7-box-icon">
                        <div class="icon icon-basic-mixer2"></div>
                      </div>
                      <h3>Tons of Shortcodes</h3>
                      <p>Sed ut perspiciatis unde omnis iste nat eror acus  antium que</p>
                    </div>
                  </div>
                      
                  <div class="col-md-6 col-sm-6">
                    <div class="fes7-box wow fadeIn"  data-wow-delay="600ms">
                      <div class="fes7-box-icon">
                        <div class="icon icon-basic-bolt"></div>
                      </div>
                      <h3>1500+ Icons</h3>
                      <p>Sed ut perspiciatis unde omnis iste nat eror acus  antium que</p>
                    </div>
                  </div>
                  
                </div>  -->
            
              </div>
            </div><!--end of row-->
          </div>
        </div>        
 
				<!-- FEATURES 8 -->
				<!-- <div class="page-section fes4-cont">
					<div class="container">
            <div class="row">
           
							<div class="col-xs-12 col-sm-4 col-md-4">
                <div class="fes8-box wow fadeIn">
								  <div class="fes8-title-cont" >
								  	<div class="fes8-box-icon">
								  		<div class="icon icon-basic-smartphone"></div>
								  	</div>
								  	<h3>RETINA READY GRAPHICS</h3>
								  </div>
								  <div>
								     Maecenas luctus nisi in sem fermentum blat. In nec  elit solliudin, elementum. 
								  </div>
								</div>
							</div>
							<div class="col-xs-12 col-sm-4 col-md-4">
                <div class="fes8-box wow fadeIn" data-wow-delay="200ms">
								  <div class="fes8-title-cont" >
								  	<div class="fes8-box-icon">
								  		<div class="icon icon-basic-mixer2"></div>
								  	</div>
								  	<h3>PARALLAX SUPPORT</h3>
								  </div>
								  <div>
								     Maecenas luctus nisi in sem fermentum blat. In nec  elit solliudin, elementum. 
								  </div>
								</div>
							</div>
              <div class="col-xs-12 col-sm-4 col-md-4">
                <div class="fes8-box wow fadeIn" data-wow-delay="400ms">
								  <div class="fes8-title-cont" >
								  	<div class="fes8-box-icon">
								  		<div class="icon icon-basic-share"></div>
								  	</div>
								  	<h3>ENDLESS POSSIBILITIES</h3>
								  </div>
								  <div>
								     Seductio maesto nisi in sem fermentum blat. In nec elit solliudin, elementum.
								  </div>
								</div>
							</div>
              
						</div>
						<div class="row">
            
              <div class="col-xs-12 col-sm-4 col-md-4">
                <div class="fes8-box wow fadeIn" data-wow-delay="600ms">
								  <div class="fes8-title-cont" >
								  	<div class="fes8-box-icon">
								  		<div class="icon icon-basic-paperplane"></div>
								  	</div>
								  	<h3>CLEAR DESIGN</h3>
								  </div>
								  <div>
								    Donec vel luctus nisi in sem fermentum blat. In nec elit solliudin, elementum.
								  </div>
								</div>
							</div>
							<div class="col-xs-12 col-sm-4 col-md-4">
                <div class="fes8-box wow fadeIn" data-wow-delay="800ms" >
								  <div class="fes8-title-cont" >
								  	<div class="fes8-box-icon">
								  		<div class="icon icon-basic-chronometer"></div>
								  	</div>
								  	<h3>POWERFUL PERFORMANCE</h3>
								  </div>
								  <div>
								    Lorem luctus antena at nisi in sem blandit. In nec elit soltudin, elementum odio. 
								  </div>
								</div>
							</div>
              <div class="col-xs-12 col-sm-4 col-md-4">
                <div class="fes8-box wow fadeIn" data-wow-delay="1000ms">
								  <div class="fes8-title-cont" >
								  	<div class="fes8-box-icon">
								  		<div class="icon icon-software-horizontal-align-center"></div>
								  	</div>
								  	<h3>FLEXIBLE WIDGETS</h3>
								  </div>
								  <div>
								    Fermentum nisi in sem fertum blat. In elit soldin, elemtum, arenam pur quam volut.
								  </div>
								</div>
							</div>              
						
            </div>
            
						<div class="row">
            
              <div class="col-xs-12 col-sm-4 col-md-4">
                <div class="fes8-box wow fadeIn" data-wow-delay="600ms">
								  <div class="fes8-title-cont" >
								  	<div class="fes8-box-icon">
								  		<div class="icon icon-basic-laptop"></div>
								  	</div>
								  	<h3>RESPONSIVE LAYOUT</h3>
								  </div>
								  <div>
								    Donec vel luctus nisi in sem fermentum blat. In nec elit solliudin, elementum, dictum pur quam volutpat suscipit antena.
								  </div>
								</div>
							</div>
							<div class="col-xs-12 col-sm-4 col-md-4">
                <div class="fes8-box wow fadeIn" data-wow-delay="800ms" >
								  <div class="fes8-title-cont" >
								  	<div class="fes8-box-icon">
								  		<div class="icon icon-music-play-button"></div>
								  	</div>
								  	<h3>HTML5 VIDEO</h3>
								  </div>
								  <div>
								    Lorem luctus antena at nisi in sem blandit. In nec elit soltudin, elementum odio et, dictum quam a volutpat elementum. 
								  </div>
								</div>
							</div>
              <div class="col-xs-12 col-sm-4 col-md-4">
                <div class="fes8-box wow fadeIn" data-wow-delay="1000ms">
								  <div class="fes8-title-cont" >
								  	<div class="fes8-box-icon">
								  		<div class="icon icon-basic-info"></div>
								  	</div>
								  	<h3>WELL DOCUMENTED</h3>
								  </div>
								  <div>
								    Fermentum nisi in sem fertum blat. In elit soldin, elemtum, arenam pur quam volutpat suscipit dictum pur quam.
								  </div>
								</div>
							</div>              
						
            </div>
					</div>
				</div> -->
                  
        <!-- VIDEO ADS 1 -->
				<!-- <div class="page-section video-ads-bg" >
					<div class="container">
            <div class="video-ads-text-cont clearfix">
              <span class="video-ads-text">BE CREATIVE</span>
              <span class="video-ads-a">
                <a class="popup-youtube" href="https://www.youtube.com/watch?v=0gv7OC9L2s8">
                  <span class="icon icon-music-play-button"></span>
                </a>
              </span>
              <span class="video-ads-text">WITH HASWELL</span>
            </div>
					</div>
				</div> -->
        
        <!-- CLIENTS 1 & TESTIMONIALS 1 -->
        <!-- <div class="page-section p-110-cont">
					<div class="container">
            <div class="row">
              <!-- CLIENTS 1 -->
              <!-- <div class="col-md-7">
                <div class="row client-row border-bot">

                    <div class="col-xs-6 col-sm-3 text-center">
                      <img alt="client" src="images/clients/1.png">
                    </div>
                  
                    <div class="col-xs-6 col-sm-3 text-center">
                      <img alt="client" src="images/clients/2.png">
                    </div>
                  
                    <div class="col-xs-6 col-sm-3 text-center">
                      <img alt="client" src="images/clients/3.png">
                    </div>
                  
                    <div class="col-xs-6 col-sm-3 text-center">
                      <img alt="client" src="images/clients/4.png">
                    </div>

                </div>
                
                <div class="row client-row">

                    <div class="col-xs-6 col-sm-3 text-center">
                      <img alt="client" src="images/clients/5.png">
                    </div>
                  
                    <div class="col-xs-6 col-sm-3 text-center">
                      <img alt="client" src="images/clients/6.png">
                    </div>
                  
                    <div class="col-xs-6 col-sm-3 text-center">
                      <img alt="client" src="images/clients/7.png">
                    </div>
                  
                    <div class="col-xs-6 col-sm-3 text-center">
                      <img alt="client" src="images/clients/8.png">
                    </div>

                </div>
                
							</div> -->
              <!-- TESTIMONIALS 1 -->
              <!-- <div class="col-md-5">
                <blockquote class="quote mb-0 m-p-0">
                  <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Harum, maiores esse temporibus accusantium quas soluta quis sed rerum.</p>
                  <footer>John Doe, Google Inc.</footer>
                 </blockquote>
							</div>
              
						</div>
					</div>
				</div> -->

        <!-- NEWS LETTER -->
        <!-- <div class="page-section nl-cont">
          <div class="container">
            <div class="relative" >
              <div id="mc_embed_signup" class="nl-form-container clearfix">
                <form action="http://abcgomel.us9.list-manage.com/subscribe/post-json?u=ba37086d08bdc9f56f3592af0&amp;id=e38247f7cc&amp;c=?" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="newsletterform validate" target="_blank" novalidate>   <!-- EDIT THIS ACTION URL (add "post-json?u" instead of "post?u" and appended "&amp;c=?" to the end of this URL) -->
                  <!-- <input type="email" value="" name="EMAIL" class="email nl-email-input" id="mce-EMAIL" placeholder="Enter your email" required> -->
                  <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
                  <!-- <div style="position: absolute; left: -5000px;"><input type="text" name="b_ba37086d08bdc9f56f3592af0_e38247f7cc" tabindex="-1" value=""></div>
          
                  <input type="submit" value="SUBSCRIBE" name="subscribe" id="mc-embedded-subscribe" class="button medium gray">
                </form>
                <div id="notification_container"  ></div>
              </div>
            </div>
          </div>
        </div> -->
        <!-- End Content -->
        
				<hr class="mt-0 mb-0">	

        <!-- Footer -->
        <?php include 'footer.php'; ?>
        <!-- End Footer -->
			</div><!-- End BG -->	
		</div><!-- End wrap -->	
        <?php include 'scripts.php'; ?>
	
	</body>
</html>		